---
version: '3.7'
services:
  security:
    image: wluisaraujo/bind9
    container_name: ns1
    dns_search: ns1.dexter.com.br
    restart: always
    network_mode: "host"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.8.8
    ports:
      - "53/udp:53/udp"
      - "5001:5001"
    expose:
      - "53/udp"
      - "53/tcp"
    extra_hosts:
      - "ns1.dexter.com.br:172.16.238.10"  
...
