---
# tasks file for iac-ansible-named-server

- name: Instala servidor Bind9 (OS base Debian)
  apt: 
    name: {{item}} 
    state: latest 
    update_cache: true 
  with_items: 
          - bind9
          - bind9utils
  register: bind_installed
  when: ansible_os_family == "Debian"
  notify:
    - Start Bind
...
