---
# tasks file for named

- name: Instala servidor Bind9 (OS base Debian)
  apt: 
    name: {{item}} 
    state: latest 
    update_cache: true 
  with_items: "{{ packages }}" 
  register: bind_installed
  when: ansible_os_family == "Debian"
  notify:
    - Start Bind
...
