---
# handlers file for named
## SystemD
- name: Start bind9
  systemd:
    state: started
    name: bind9.service
    enabled: yes
    force: yes
  ignore_errors: yes
  when:
    - ansible_service_mgr == "systemd"

- name: Stop bind9
  systemd:
    state: stopped
    name: bind9.service
    enabled: yes
    force: yes
  ignore_errors: yes
  when:
    - ansible_service_mgr == "systemd"

- name: Restart bind9
  systemd:
    state: restarted
    name: bind9.service
    force: yes
  ignore_errors: yes
  when:
    - ansible_service_mgr == "systemd"

- name: Reload bind9
  systemd:
    state: reloaded
    name: bind9.service
    force: yes
  ignore_errors: yes
  when:
    - ansible_service_mgr == "systemd"

## SystemV
- name: Start bind9
  service:
    state: started
    name: bind9
    enabled: yes
  when:
    - ansible_service_mgr == "service"

- name: Stop bind9
  service:
    state: stopped
    name: bind9
    enabled: yes
  when:
    - ansible_service_mgr == "service"

- name: Restart bind9
  service:
    state: restarted
    name: bind9
  when:
    - ansible_service_mgr == "service"

- name: Reload bind9
  service:
    state: reloaded
    name: bind9
  when:
    - ansible_service_mgr == "service"
...
